### ISSUE TITLE
Public API

### ISSUE THREAD

**Issue by SebastianM-C** [SciML/UDEComponents.jl#9]
The main feature so far in the package is creating a ODESystem with a neural network inside. Comparing this to the MTKStdlib, this seems like a Block.

@ChrisRackauckas Would `NeuralNetworkBlock` be a good name?

Besides that, we also have a small utility for creating simple Lux models, should that be renamed?

Other than that, what should we add in here?

Would it make sense to add components in the future that are similar to the electrical, thermal etc. components?

**Comment by ChrisRackauckas** [comment]
> @ChrisRackauckas Would NeuralNetworkBlock be a good name?

Yes

> Besides that, we also have a small utility for creating simple Lux models, should that be renamed?

What's the API there?

> Other than that, what should we add in here?

I don't think anything else is needed, other specifying units of inputs and outputs.

**Comment by ChrisRackauckas** [comment]
> Would it make sense to add components in the future that are similar to the electrical, thermal etc. components?

That should just be handled by units. You don't need acausal connectors here, and so you don't need the special pieces other than RealInput and RealOutput like connectivity.

**Comment by SebastianM-C** [comment]
> What's the API there?

`multi_layer_feed_forward(input_length, output_length; width::Int = 5, depth::Int = 1, activation = tanh, disable_optimizations = false)`
